/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Menumakanan extends javax.swing.JFrame {

    /**
     * Creates new form Menumakanan
     */
    public Menumakanan() {
        initComponents();
        setTitle("Katsuya Resto App");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxchickenkatsu = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtbanyak1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtbanyak2 = new javax.swing.JTextField();
        cbxricebowl = new javax.swing.JCheckBox();
        txtbanyak3 = new javax.swing.JTextField();
        cbxeggroll = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        cbxramen = new javax.swing.JCheckBox();
        txtbanyak4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtbanyak5 = new javax.swing.JTextField();
        cbxtakoyaki = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtbanyak6 = new javax.swing.JTextField();
        cbxesteh = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txtbanyak7 = new javax.swing.JTextField();
        cbxcappucino = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        cbxlemontea = new javax.swing.JCheckBox();
        txtbanyak8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtbanyak9 = new javax.swing.JTextField();
        cbxjusjeruk = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextarea = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Makanan");

        jLabel2.setText("Harga");

        jLabel3.setText("Banyak");

        jLabel4.setText("Minuman");

        jLabel5.setText("Harga");

        jLabel6.setText("Banyak");

        cbxchickenkatsu.setText("Chicken Katsu");

        jLabel7.setText("Rp. 18000");

        jLabel8.setText("Rp. 15000");

        cbxricebowl.setText("Rice Bowl");

        cbxeggroll.setText("Egg Roll");

        jLabel9.setText("Rp. 21000");

        cbxramen.setText("Ramen");

        jLabel10.setText("Rp. 20000");

        cbxtakoyaki.setText("Takoyaki");

        jLabel11.setText("Rp. 18000");

        txtbanyak6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanyak6ActionPerformed(evt);
            }
        });

        cbxesteh.setText("Es Teh");
        cbxesteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxestehActionPerformed(evt);
            }
        });

        jLabel12.setText("Rp. 5000");

        txtbanyak7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanyak7ActionPerformed(evt);
            }
        });

        cbxcappucino.setText("Cappucino");
        cbxcappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcappucinoActionPerformed(evt);
            }
        });

        jLabel13.setText("Rp. 8000");

        cbxlemontea.setText("Lemon Tea");
        cbxlemontea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxlemonteaActionPerformed(evt);
            }
        });

        txtbanyak8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanyak8ActionPerformed(evt);
            }
        });

        jLabel14.setText("Rp. 7000");

        txtbanyak9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanyak9ActionPerformed(evt);
            }
        });

        cbxjusjeruk.setText("Jus Jeruk");
        cbxjusjeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxjusjerukActionPerformed(evt);
            }
        });

        jLabel15.setText("Rp. 9000");

        jLabel16.setText("Menu Yang Dipesan");

        jtextarea.setColumns(20);
        jtextarea.setRows(5);
        jScrollPane1.setViewportView(jtextarea);

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cbxchickenkatsu)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel1)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel2)))
                                .addGap(40, 44, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtbanyak1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxricebowl)
                                    .addComponent(cbxeggroll)
                                    .addComponent(cbxramen)
                                    .addComponent(cbxtakoyaki))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtbanyak2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbanyak4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtbanyak5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtbanyak3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxcappucino)
                                    .addComponent(cbxlemontea)
                                    .addComponent(cbxjusjeruk)
                                    .addComponent(cbxesteh))
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtbanyak6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbanyak7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbanyak8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbanyak9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnpesan)
                                .addGap(27, 27, 27)
                                .addComponent(btnreset))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxchickenkatsu)
                    .addComponent(jLabel7)
                    .addComponent(txtbanyak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxesteh)
                    .addComponent(jLabel12)
                    .addComponent(txtbanyak6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxcappucino)
                            .addComponent(jLabel13)
                            .addComponent(txtbanyak7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxlemontea)
                            .addComponent(jLabel14)
                            .addComponent(txtbanyak8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxjusjeruk)
                            .addComponent(jLabel15)
                            .addComponent(txtbanyak9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxricebowl)
                            .addComponent(jLabel8)
                            .addComponent(txtbanyak2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxeggroll)
                            .addComponent(jLabel9)
                            .addComponent(txtbanyak3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxramen)
                            .addComponent(txtbanyak4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxtakoyaki)
                            .addComponent(jLabel11)
                            .addComponent(txtbanyak5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpesan)
                    .addComponent(btnreset))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxestehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxestehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxestehActionPerformed

    private void txtbanyak6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanyak6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanyak6ActionPerformed

    private void txtbanyak7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanyak7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanyak7ActionPerformed

    private void cbxcappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcappucinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxcappucinoActionPerformed

    private void cbxlemonteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxlemonteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxlemonteaActionPerformed

    private void txtbanyak8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanyak8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanyak8ActionPerformed

    private void txtbanyak9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanyak9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanyak9ActionPerformed

    private void cbxjusjerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxjusjerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxjusjerukActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        String tampil;
        tampil = "";
        int bayar = 0;
        if(cbxchickenkatsu.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak1.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil +=cbxchickenkatsu.getText()+" Rp.18000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxricebowl.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak2.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil +=cbxricebowl.getText()+" Rp.15000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxeggroll.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak3.getText());
            int total;
            total=jumlah*21000;
            bayar=bayar+total;
            tampil +=cbxeggroll.getText()+" Rp.21000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxramen.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak4.getText());
            int total;
            total=jumlah*20000;
            bayar=bayar+total;
            tampil +=cbxramen.getText()+" Rp.20000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxtakoyaki.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak5.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil +=cbxtakoyaki.getText()+" Rp.18000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxesteh.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak6.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil +=cbxesteh.getText()+" Rp.5000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxcappucino.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak7.getText());
            int total;
            total=jumlah*8000;
            bayar=bayar+total;
            tampil +=cbxcappucino.getText()+" Rp.8000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxlemontea.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak8.getText());
            int total;
            total=jumlah*7000;
            bayar=bayar+total;
            tampil +=cbxlemontea.getText()+" Rp.7000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxjusjeruk.isSelected()){
            int jumlah=Integer.parseInt(txtbanyak9.getText());
            int total;
            total=jumlah*9000;
            bayar=bayar+total;
            tampil +=cbxjusjeruk.getText()+" Rp.9000"+" x "+jumlah+" = "+total+"\n";
    }//GEN-LAST:event_btnpesanActionPerformed
      jtextarea.setText(tampil+"==============================="+"\n"+"Totalnya="+bayar);
    }
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
      txtbanyak1.setText("");
      txtbanyak2.setText("");
      txtbanyak3.setText("");
      txtbanyak4.setText("");
      txtbanyak5.setText("");
      txtbanyak6.setText("");
      txtbanyak7.setText("");
      txtbanyak8.setText("");
      txtbanyak9.setText("");
      jtextarea.setText("");
    }//GEN-LAST:event_btnresetActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menumakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox cbxcappucino;
    private javax.swing.JCheckBox cbxchickenkatsu;
    private javax.swing.JCheckBox cbxeggroll;
    private javax.swing.JCheckBox cbxesteh;
    private javax.swing.JCheckBox cbxjusjeruk;
    private javax.swing.JCheckBox cbxlemontea;
    private javax.swing.JCheckBox cbxramen;
    private javax.swing.JCheckBox cbxricebowl;
    private javax.swing.JCheckBox cbxtakoyaki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtextarea;
    private javax.swing.JTextField txtbanyak1;
    private javax.swing.JTextField txtbanyak2;
    private javax.swing.JTextField txtbanyak3;
    private javax.swing.JTextField txtbanyak4;
    private javax.swing.JTextField txtbanyak5;
    private javax.swing.JTextField txtbanyak6;
    private javax.swing.JTextField txtbanyak7;
    private javax.swing.JTextField txtbanyak8;
    private javax.swing.JTextField txtbanyak9;
    // End of variables declaration//GEN-END:variables
}
